version: '3'

services:
  db:
    image: postgres:12
    container_name: db
    environment:
      POSTGRES_PASSWORD: example
  backend:
    container_name: backend
    build: 
      context: .
      dockerfile: ./backend/app/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/backend
    ports:
      - "8000:8000"
    depends_on:
      - db
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: ./frontend/app/Dockerfile
    command: ["npm", "start"]
    volumes:
      - '.:/frontend'
      - '/frontend/node_modules'
    ports:
      - "3000:3000"
