version: '3'

services:
  db:
    image: postgres:12
    container_name: db
    environment:
      POSTGRES_PASSWORD: example
  backend:
    container_name: backend
    build: ./backend/app/
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/app/:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
  frontend:
    container_name: frontend
    build: ./frontend/app/
    command: ["npm", "start"]
    volumes:
      - ./frontend/app/:/app
      - '/frontend/app/:/app/node_modules'
    ports:
      - "3000:3000"
